### ISSUE TITLE
php size limits are stuck at 100M

### ISSUE THREAD

**Issue by hess8** [LycheeOrg/Lychee-Docker#109]
I've done all I can think of to get the max file and post sizes to change (hrs...).  

**Lychee is stuck at 100M limits** 
    DB Version:                      4.3.4
    System:                          Linux
    PHP Version:                     7.4
    Max uploaded file size:          100M
    Max post size:                   100M

I've changed the sizes to 1024M in php.ini and another php_uploads.ini to conf/ 

As seen in a grep (same for max_upload_filesize), the .ini files have the right values:
- /etc/php/7.4/cli/php.ini:post_max_size = 1024M
- /home/photoserver/lychee/conf/php_uploads.ini:post_max_size = 1024M

**..but the container is stuck at an 8M limit** , even though **Inspect** says it's **binding to these php.ini files** I'm working with.  So somehow Lychee is ignoring my settings (higher) and the container settings (way too low)
```
/var/lib/docker/overlay2/08b24cfb4a971b48bad1500a60f4fee808a0dfd523060bffdcf55e0013188025/merged/etc/php/7.4/cli/php.ini:post_max_size = 8M
/var/lib/docker/overlay2/08b24cfb4a971b48bad1500a60f4fee808a0dfd523060bffdcf55e0013188025/merged/etc/php/7.4/fpm/php.ini:post_max_size = 8M
/var/lib/docker/overlay2/08b24cfb4a971b48bad1500a60f4fee808a0dfd523060bffdcf55e0013188025/diff/etc/php/7.4/cli/php.ini:post_max_size = 8M
/var/lib/docker/overlay2/2ff3eadeb911d03af089f729da17f0e98b3fa1cb44b0d31fd3e25e26a93f275d/diff/etc/php/7.4/cli/php.ini:post_max_size = 8M
/var/lib/docker/overlay2/2ff3eadeb911d03af089f729da17f0e98b3fa1cb44b0d31fd3e25e26a93f275d/diff/etc/php/7.4/fpm/php.ini:post_max_size = 8M
```

**How can I get my settings into Lychee?**   Is 100M somehow fixed in the code?

FYI here is my minimal docker-compose file:

 ```
mariadb:
   image: ghcr.io/linuxserver/mariadb:latest
   container_name: lychee_mariadb
   restart: always
   volumes:
     - /path/to/mariadb/data:/config
  lychee:
    image: lycheeorg/lychee
    container_name: lychee
    restart: always
    volumes:
      - ./lychee/conf:/conf
      - ./lychee/uploads:/uploads
      - ./lychee/sym:/sym
      - ./uploads.ini:/etc/php/7.4/cli/conf.d/uploads.ini
    environment:
      - TZ=America/Denver
    ports:
      - 8080:80
```
