### ISSUE TITLE
Running on subpath with nginx

### ISSUE THREAD

**Issue by azertylr** [LycheeOrg/Lychee-Docker#181]
Hello I've tried to run as a subpath using nginx but I doesn't work, it redirect without the supath :(

This is my docker-compose:
```
  lychee:
    image: lycheeorg/lychee
    #image: lscr.io/linuxserver/lychee:latest
    container_name: lychee
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/conf/db.sqlite
      - APP_NAME=Lychee 
      - APP_URL='https://vps.loris-rion.fr:443'
      - APP_DIR='/lychee'
      - TRUSTED_PROXIES=swag
```

and nginx config

```
location /lychee/ {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app lychee;
    set $upstream_port 80;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    rewrite /lychee(.*) $1 break;
}

thanks

```
