### ISSUE TITLE
Photos won't show up in gallery

### ISSUE THREAD

**Issue by Tiritibambix** [LycheeOrg/Lychee-Docker#190]
Hello.

I've been experiencing random errors since last upgrade.

When I upload photos to an album, some of them just won't show up. I have to double check, list the ones missing and re-upload them.

I checked the logs but I found literally nothing about this.

Here's my docker-compose:
```
version: '3'

services:
  lychee_db:
    container_name: lychee_db
    image: mariadb:11
    environment:
      - MYSQL_ROOT_PASSWORD=**********
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=**********
    expose: 
      - 3306
    volumes:
      - /srv/dev-disk-by-uuid-7fe66601-5ca0-4c09-bc13-a015025fe53a/Files/Lychee/mysql:/var/lib/mysql
    networks:
      - lychee
    restart: unless-stopped

  lychee:
    image: lycheeorg/lychee
    container_name: lychee
    ports:
      - 6996:80
    volumes:
      - /srv/dev-disk-by-uuid-7fe66601-5ca0-4c09-bc13-a015025fe53a/Files/Lychee/lychee/conf:/conf
      - /srv/dev-disk-by-uuid-7fe66601-5ca0-4c09-bc13-a015025fe53a/Files/Lychee/lychee/uploads:/uploads
      - /srv/dev-disk-by-uuid-7fe66601-5ca0-4c09-bc13-a015025fe53a/Files/Lychee/lychee/sym:/sym
    networks:
      - lychee
    environment:
      - PUID=998
      - PGID=100
      - PHP_TZ=Europe/Paris
      - TIMEZONE=Europe/Paris
      - APP_URL=https://my.domain.tld
      - DB_CONNECTION=mysql
      - DB_HOST=lychee_db
      - DB_PORT=3306
      - DB_DATABASE=lychee
      - DB_USERNAME=lychee
      - DB_PASSWORD=**********
      - STARTUP_DELAY=30
      - TRUSTED_PROXIES=*
    restart: unless-stopped
    depends_on:
      - lychee_db

networks:
  lychee:

volumes:
  mysql:
```

My NginxProxyManager settings for this domain:
```
fastcgi_param HTTPS on;
```

How can I fix that please ?
Thanks for your help.
