### ISSUE TITLE
Lychee won't work after host reboot

### ISSUE THREAD

**Issue by Szparki** [LycheeOrg/Lychee-Docker#201]
The host on what my Lychee containers were running was rebooted. Now when I run a `docker compose up` I get into the initial setup mode (upon accessing Lychee's URL I get redirected to to my-lychee-url//install). If I proceed with the install I do get a not very useful error. Any ideas?

<img width="275" alt="lychee installer" src="https://github.com/LycheeOrg/Lychee-Docker/assets/8669658/a373f1b6-cc4c-4e3e-ac42-61a64c64132e">
<img width="384" alt="lychee error" src="https://github.com/LycheeOrg/Lychee-Docker/assets/8669658/8e443e77-e808-4390-8b30-026b18646242">

```

---
services:
  lychee_db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: lychee_db
    restart: always
    networks:
      - private
    volumes:
      - /data/lychee/db:/config
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=password
      - PGID=990
      - PUID=1005
      - TZ=Etc/UTC
    mem_limit: 500m
    memswap_limit: 1024m
    mem_reservation: 100m
    cpus: 1

  lychee:
    image: lscr.io/linuxserver/lychee:4.13.0
    #image: lscr.io/linuxserver/lychee:5.0.0
    container_name: lychee
    restart: always
    networks:
      - private
    volumes:
      - /data/lychee/config:/config
      - /data/lychee/pictures:/pictures
      - /data/lychee/logs:/logs
    environment:
      - DB_HOST=lychee_db
      - DB_USERNAME=lychee
      - DB_PASSWORD=password
      - DB_DATABASE=lychee
      - DB_PORT=3306
      - DB_CONNECTION=mysql
      - PGID=1005
      - PUID=1005
      - TZ=Etc/UTC
      - PHP_TZ=UTC
    #  - APP_KEY=appkey
    #  - APP_URL=http://localhost:8086
    #  - APP_FORCE_HTTPS=false
    ports:
      - 8080:80
    mem_limit: 500m
    memswap_limit: 1024m
    mem_reservation: 200m
    cpus: 1
    depends_on:
      - lychee_db

networks:
  private:
```
