### ISSUE TITLE
new deploy with installer won't work

### ISSUE THREAD

**Issue by Szparki** [LycheeOrg/Lychee-Docker#202]
This is a brand new deployment on Ubuntu 22.04 using almost the default docker compose file:
```
services:
  lychee_db:
    container_name: lychee_db
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=pass
    #expose:
    #  - 3306
    volumes:
      - /data/lychee/db:/var/lib/mysql
    networks:
      - lychee
    restart: unless-stopped

  lychee:
    image: lycheeorg/lychee
    container_name: lychee
    ports:
      - 8086:80
    volumes:
      - /data/lychee/config:/conf
      - /data/lychee/uploads:/uploads
      - /data/lychee/sym:/sym
      - /data/lychee/logs:/logs
    networks:
      - lychee
    environment:
      - PUID=1005
      - PGID=1005
      - PHP_TZ=UTC
      - TIMEZONE=UTC
      - DB_CONNECTION=mysql
      - DB_HOST=lychee_db
      - DB_PORT=3306
      - DB_DATABASE=lychee
      - DB_USERNAME=lychee
      - DB_PASSWORD=pass
      - MAIL_DRIVER=smtp
      - MAIL_HOST=my.smtp.server
      - MAIL_PORT=25
      - MAIL_ENCRYPTION=null
      - STARTUP_DELAY=30
    restart: unless-stopped
    depends_on:
      - lychee_db

networks:
  lychee:

volumes:
  mysql:
```
The directories with the proper permissions exists on the host server:
```
% id lychee
uid=1005(lychee) gid=1005(lychee) groups=1005(lychee)
% stat /data/lychee/
  File: /data/lychee/
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 803h/2051d	Inode: 1186313     Links: 8
Access: (0755/drwxr-xr-x)  Uid: ( 1005/  lychee)   Gid: ( 1005/  lychee)
Access: 2024-07-07 23:47:20.297317022 +0000
Modify: 2024-07-07 23:43:50.425224395 +0000
Change: 2024-07-07 23:43:50.425224395 +0000
 Birth: 2024-07-07 23:41:44.759563137 +0000

% ll /data/lychee
total 24
drwxr-xr-x  2 lychee           lychee           4096 Jul  7 23:42 conf
drwxr-xr-x  2 root             root             4096 Jul  7 23:46 config
drwxr-xr-x  6 systemd-coredump systemd-coredump 4096 Jul  7 23:52 db
drwxrwsr-x  2 lychee           lychee           4096 Jul  7 23:44 logs
drwxrwsr-x  2 lychee           lychee           4096 Jul  7 23:44 sym
drwxrwsr-x 11 lychee           lychee           4096 Jul  7 23:44 uploads
```

When I access the website I get the following screen, and if I click the "Create admin account" nothing happens. I tried Firefox and Safari.
<img width="879" alt="Lychee-installer" src="https://github.com/LycheeOrg/Lychee-Docker/assets/8669658/e5fe2497-ba2b-47a3-b530-cf46503a30f1">
Do you have any ideas what should I try?
