### ISSUE TITLE
Error 500 clean install SQL migration problem

### ISSUE THREAD

**Issue by Webrow** [LycheeOrg/Lychee-Docker#204]
```
version: "3"
#-------------------------------------------
#  Docker Compose
# @RobLandry
# Repo : https://github.com/LycheeOrg/Lychee-Docker
#-------------------------------------------
services:
  lychee_db:
    container_name: lychee_db
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=QWERTYUIOPA1234567890
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=QWERTYUIOPASDFGHJKLCVB
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - lychee
    restart: unless-stopped
  lychee:
    image: lycheeorg/lychee
    container_name: lychee
    ports:
      - 8161:80
    volumes:
      - ./lychee/conf:/conf
      - ./lychee/uploads:/uploads
      - ./lychee/sym:/sym
      - ./lychee/logs:/logs
    networks:
      - lychee
    environment:
      #- PUID=1000
      #- PGID=1000
      # PHP timezone e.g. PHP_TZ=America/New_York
      - PHP_TZ=UTC
      - TIMEZONE=UTC
      #- APP_NAME=Laravel
      #- APP_ENV=local
      #- APP_DEBUG=true
      #- APP_FORCE_HTTPS=false
        #- APP_URL=http://localhost:8161
      #- APP_DIR=
      #- DEBUGBAR_ENABLEd=false
      #- LEGACY_V4_REDIRECT=false
      #- DB_OLD_LYCHEE_PREFIX=''
      - DB_CONNECTION=mysql
      - DB_HOST=lychee_db
      - DB_PORT=3306
      - DB_DATABASE=lychee
      - DB_USERNAME=lychee
      - DB_PASSWORD=QWERTYUIOPASDFGHJKLCVB
      #- DB_PASSWORD_FILE=<filename>
      #- DB_PASSWORD_FILE=<filename>
      #- DB_LOG_SQL=false
      #- DB_LOG_SQL_EXPLAIN=false
      #- ENABLE_TOKEN_AUTH=true
      #- CACHE_DRIVER=file
      #- SESSION_DRIVER=file
      #- SESSION_LIFETIME=120
      #- QUEUE_CONNECTION=sync
      #- SECURITY_HEADER_HSTS_ENABLE=false
      #- SECURITY_HEADER_CSP_CONNECT_SRC=
      #- SECURITY_HEADER_SCRIPT_SRC_ALLOW=
      #- SESSION_SECURE_COOKIE=false
      #- MAIL_DRIVER=smtp
      #- MAIL_HOST=smtp.mailtrap.io
      #- MAIL_PORT=2525
      #- MAIL_USERNAME=null
      #- MAIL_PASSWORD=null
      #- MAIL_PASSWORD_FILE=<filename>
      #- MAIL_ENCRYPTION=null
      #- MAIL_FROM_NAME=
      #- MAIL_FROM_ADDRESS=
      #- TRUSTED_PROXIES=
      #- SKIP_PERMISSIONS_CHECKS
      - STARTUP_DELAY=30
      #- ADMIN_USER=admin
      #- ADMIN_PASSWORD=<ADMIN_PASSWORD>
      #- ADMIN_PASSWORD_FILE=<filename>
      ### Unused in Lychee
      #- REDIS_HOST=127.0.0.1
      #- REDIS_PASSWORD=null
      #- REDIS_PASSWORD_FILE=<filename>
      #- REDIS_PORT=6379
    restart: unless-stopped
    depends_on:
      - lychee_db
networks:
  lychee:
volumes:
  mysql:
```                                        

HttpException

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'generation_expression' in 'field list' (Connection: mysql, SQL: select column_name as `name`, data_type as `type_name`, column_type as `type`, collation_name as `collation`, is_nullable as `nullable`, column_default as `default`, column_comment as `comment`, generation_expression as `expression`, extra as `extra` from information_schema.columns where table_schema = 'lychee' and table_name = 'users' order by ordinal_position asc)

| |  | | | |/ __|  _ \ / _ \/ _ \
 | |__| |_| | (__| | | |  __/  __/
 |_____\__, |\___|_| |_|\___|\___|
       |___/

-------------------------------------
Lychee Version: 5.5.1 (release)
Lychee Branch:  master
Lychee Commit:  656ffae
https://github.com/LycheeOrg/Lychee/commit/656ffaed2027da370b0b84cdd6d846d5fa5c028f
-------------------------------------
**** Delaying startup (30 seconds)... ****
**** Make sure the /conf /uploads /sym /logs folders exist ****
**** Create the symbolic link for the /uploads folder ****
**** Create the symbolic link for the /sym folder ****
**** Create the symbolic link for the /logs folder ****
**** Copy the .env to /conf ****
**** Inject .env values ****
**** Generate the key (to make sure that cookies cannot be decrypted etc) ****

                           APPLICATION IN PRODUCTION.

   WARN  Command cancelled.

**** Migrate the database ****

   INFO  Running migrations.

  2019_09_28_171753_config_fix ................................... 3.94ms FAIL

In Connection.php line 813:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'generation_expressi
  on' in 'field list' (Connection: mysql, SQL: select column_name as `name`,
  data_type as `type_name`, column_type as `type`, collation_name as `collati
  on`, is_nullable as `nullable`, column_default as `default`, column_comment
   as `comment`, generation_expression as `expression`, extra as `extra` from
   information_schema.columns where table_schema = 'lychee' and table_name =
  'configs' order by ordinal_position asc)

In Connection.php line 407:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'generation_expressi
  on' in 'field list'

**** Make sure user.css exists and symlink it ****
**** Make sure custom.js exists and symlink it ****
**** Create user and use PUID/PGID ****
        User UID :      1000
        User GID :      1000
**** Make sure Laravel's log exists ****
**** Set Permissions ****
**** Start cron daemon ****
Starting periodic command scheduler: cron.
**** Setup complete, starting the server. ****
127.0.0.1 - - [22/Jul/2024:08:18:21 +0000] "GET / HTTP/1.1" 500 2256 "-" "curl/7.88.1" "-"
127.0.0.1 - - [22/Jul/2024:08:18:51 +0000] "GET / HTTP/1.1" 500 2256 "-" "curl/7.88.1" "-"
172.23.0.1 - - [22/Jul/2024:08:19:11 +0000] "GET / HTTP/1.0" 500 2244 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0" "84.241.200.13"
172.23.0.1 - - [22/Jul/2024:08:19:12 +0000] "GET / HTTP/1.0" 500 2244 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0" "84.241.200.13"
