### ISSUE TITLE
Loop install page while install Lychee

### ISSUE THREAD

**Issue by Mowen-M** [LycheeOrg/Lychee-Docker#210]
When i install lychee, it loop in the install page. And I met 500 ,403 errors also in the when i trying docker install 

Here is the video link
https://youtu.be/z5GPdghSmz4

```yaml
#-------------------------------------------
#  Docker Compose
# @RobLandry
# Repo : https://github.com/LycheeOrg/Lychee-Docker
#-------------------------------------------

services:
  lychee_db:
    container_name: lychee_db
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=Mowen
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=Mowen
    expose: 
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - lychee
    restart: unless-stopped

  lychee:
    image: lycheeorg/lychee
    container_name: lychee
    ports:
      - 2585:80
    volumes:
      - /volume8/docker/lychee/conf:/conf
      - /volume8/docker/lychee/uploads:/uploads
      - /volume8/docker/lychee/sym:/sym
      - /volume8/docker/lychee/logs:/logs
      - /volume8/docker/lychee/tmp:/lychee-tmp
    networks:
      - lychee
    environment:
      #- PUID=1000
      #- PGID=1000
      # PHP timezone e.g. PHP_TZ=America/New_York
      - PHP_TZ=Asia/Shanghai
      - TIMEZONE=Asia/Shanghai
      #- APP_NAME=Laravel
      #- APP_ENV=local
      #- APP_DEBUG=true
      #- APP_FORCE_HTTPS=false
      #- APP_URL=http://localhost
      #- APP_DIR=
      #- DEBUGBAR_ENABLEd=false
      #- VUEJS_ENABLED=true
      #- LEGACY_API_ENABLED=false
      #- LEGACY_V4_REDIRECT=false
      #- DB_OLD_LYCHEE_PREFIX=''
      - DB_CONNECTION=mysql
      - DB_HOST=lychee_db
      - DB_PORT=3306
      - DB_DATABASE=lychee
      - DB_USERNAME=lychee
      - DB_PASSWORD=Mowen
      #- DB_PASSWORD_FILE=<filename>
      #- DB_LOG_SQL=false
      #- DB_LOG_SQL_EXPLAIN=false
      #- ENABLE_TOKEN_AUTH=true
      #- CACHE_DRIVER=file
      #- SESSION_DRIVER=file
      #- SESSION_LIFETIME=120
      #- QUEUE_CONNECTION=sync
      #- SECURITY_HEADER_HSTS_ENABLE=false
      #- SECURITY_HEADER_CSP_CONNECT_SRC=
      #- SECURITY_HEADER_SCRIPT_SRC_ALLOW=
      #- SESSION_SECURE_COOKIE=false
      #- MAIL_DRIVER=smtp
      #- MAIL_HOST=smtp.mailtrap.io
      #- MAIL_PORT=2525
      #- MAIL_USERNAME=null
      #- MAIL_PASSWORD=null
      #- MAIL_PASSWORD_FILE=<filename>
      #- MAIL_ENCRYPTION=null
      #- MAIL_FROM_NAME=
      #- MAIL_FROM_ADDRESS=
      #- TRUSTED_PROXIES=
      #- SKIP_PERMISSIONS_CHECKS
      - STARTUP_DELAY=30
      #- ADMIN_USER=admin
      #- ADMIN_PASSWORD=<ADMIN_PASSWORD>
      #- ADMIN_PASSWORD_FILE=<filename>
      ### Unused in Lychee
      #- REDIS_HOST=127.0.0.1
      #- REDIS_PASSWORD=null
      #- REDIS_PASSWORD_FILE=<filename>
      #- REDIS_PORT=6379
    restart: unless-stopped
    depends_on:
      - lychee_db

networks:
  lychee:

volumes:
  mysql:
```

**Comment by ildyria** [comment]
I think you may be missing the hostname in the db side.
Here is the one that I use.

```yaml
services:
  lychee_db:
    container_name: Lychee-DB
    hostname: lychee-db
    image: mariadb:11
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ:-Europe/Amsterdam}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    expose: 
      - 3306
    volumes:
      - ${PATH_TO_DB:-.}/mysql:/var/lib/mysql
    networks:
      - lychee
    restart: unless-stopped

  lychee:
    image: lycheeorg/lychee:latest
    container_name: Lychee-Core
    security_opt:
      - no-new-privileges:true
    ports:
      - 90:80
    volumes:
      - ${PATH_TO_FILES:-.}/lychee/conf:/conf
      - ${PATH_TO_FILES:-.}/lychee/uploads:/uploads
      - ${PATH_TO_FILES:-.}/lychee/sym:/sym
      - ${PATH_TO_FILES:-.}/lychee/logs:/logs
      - ${PATH_TO_FILES:-.}/lychee/tmp:/lychee-tmp
    env_file:
      - path: ./.env
        required: false
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      # PHP timezone e.g. PHP_TZ=America/New_York
      - PHP_TZ=${TZ:-Europe/Amsterdam}
      - TIMEZONE=${TZ:-Europe/Amsterdam}
      - APP_NAME=${APP_NAME:-Laravel}
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_FORCE_HTTPS=${APP_FORCE_HTTPS:-false}
      #- APP_DIR=
      - APP_URL=${APP_URL:-https://localhost}
      #- DEBUGBAR_ENABLEd=false
      - LEGACY_V4_REDIRECT=${LEGACY_V4_REDIRECT:-false}
      #- DB_OLD_LYCHEE_PREFIX=''
      - DB_CONNECTION=mysql
      - DB_HOST=lychee-db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      #- DB_PASSWORD_FILE=<filename>
      #- DB_LOG_SQL=false
      #- DB_LOG_SQL_EXPLAIN=false
      - ENABLE_TOKEN_AUTH=${ENABLE_TOKEN_AUTH:-true}
      #- CACHE_DRIVER=file
      #- SESSION_DRIVER=file
      #- SESSION_LIFETIME=120
      #- QUEUE_CONNECTION=sync
      #- SECURITY_HEADER_HSTS_ENABLE=false
      #- SECURITY_HEADER_CSP_CONNECT_SRC=
      #- SECURITY_HEADER_SCRIPT_SRC_ALLOW=
      #- SESSION_SECURE_COOKIE=false
      #- MAIL_DRIVER=smtp
      #- MAIL_HOST=smtp.mailtrap.io
      #- MAIL_PORT=2525
      #- MAIL_USERNAME=null
      #- MAIL_PASSWORD=null
      #- MAIL_PASSWORD_FILE=<filename>
      #- MAIL_ENCRYPTION=null
      #- MAIL_FROM_NAME=
      #- MAIL_FROM_ADDRESS=
      - STARTUP_DELAY=30
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
      #- SKIP_PERMISSIONS_CHECKS
      - STARTUP_DELAY=10
      #- ADMIN_USER=admin
      #- ADMIN_PASSWORD=<ADMIN_PASSWORD>
      #- ADMIN_PASSWORD_FILE=<filename>
      ### Unused in Lychee
      #- REDIS_HOST=127.0.0.1
      #- REDIS_PASSWORD=null
      #- REDIS_PASSWORD_FILE=<filename>
      #- REDIS_PORT=6379
    restart: unless-stopped
    depends_on:
      - lychee_db
    networks:
      - lychee
      - traefik-servicenet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photography.rule=Host(`photography.${DOMAIN_NAME1}`)"
      - "traefik.http.routers.photography.entrypoints=websecure"
      - "traefik.http.routers.photography.tls.certresolver=myresolver"
      - "traefik.http.middlewares.https-photography.headers.sslproxyheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.photography.middlewares=https-photography"

networks:
  lychee:
    internal: true
```
