### ISSUE TITLE
Trying to move lychee stack from portainer to komodo, access denied for user lychee to database

### ISSUE THREAD

**Issue by scsa20** [LycheeOrg/Lychee-Docker#220]
Hello everyone,

I am trying to move over configurations and such from portainer to komodo for docker management. Right now the way portainer is set up I have 3 instances, the main entry point that's on my local network and 2 remote agents, one of which is on my web server hosted elsewhere. As of now Komodo is set up in a similar way, deployed on my main server here on my local network with a remote agent on my web server.

Lychee is currently deployed to the remote location done from my main location. When deploying the stack from portainer, everything loads just fine. Now trying to copy the stack details over to Komodo (legit 1:1) I get the following error: [Warning] Access denied for user 'lychee'@'%' to database '/var/www/html/Lychee/database/database.sqlite'

I double, tripled, quadruple checked everything and I do not see anything that would cause Lychee not connect to the database unless I am just completely blind. Any help with figuring this out will be helpful.

Here is the docker compose from portainer:

```
#-------------------------------------------
#  Docker Compose
# @RobLandry
# Repo : https://github.com/LycheeOrg/Lychee-Laravel-Docker
#-------------------------------------------

version: '3'

services:
  lychee_db:
    container_name: lychee_db
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=*********
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=*********
    expose: 
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - lychee
    restart: unless-stopped

  lychee:
    image: lycheeorg/lychee:nightly
    container_name: lychee
    ports:
      - 90:80
    volumes:
      - /data/lychee/conf:/conf
      - /data/lychee/uploads:/uploads
      - /data/lychee/sym:/sym
    networks:
      - lychee

    env_file:
      stack.env
    restart: unless-stopped
    depends_on:
      - lychee_db

networks:
  lychee:

volumes:
  mysql:
```

Only difference with the version on komodo is the removal of env_file: stack.env.

Here is the env I've added to komodo which to my understanding will write to .env and use that (it's the same from portainer):

```
PHP_TZ=America/Phoenix
TIMEZONE=America/Phoenix
APP_FORCE_HTTPS=true
APP_URL=https://url.domain.tl
TRUSTED_PROXIES=*
DB_CONNECTION=mysql
DB_HOST=lychee_db
DB_PORT=3306
DB_DATABASE=lychee
DB_USERNAME=lychee
DB_PASSWORD=*********
MAIL_DRIVER=smtp
MAIL_HOST=smtp.server.domain.tld
MAIL_PORT=25
STARTUP_DELAY=30
```

Again, any assistance would be great (and yes it happens with latest as well).
