### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by gxgani** [LycheeOrg/Lychee-Docker#88]
compose-yaml:
```yaml
---
version: '3'

services:
  lychee_db:
    container_name: lychee_db
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=${DB_PASSWORD}
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - lychee
    restart: unless-stopped

  lychee:
    image: lycheeorg/lychee:latest
    container_name: lychee
    ports:
      - 8142:80
    volumes:
      - ./lychee/conf:/conf
      - ./lychee/uploads:/uploads
      - ./lychee/sym:/sym
    networks:
      - lychee
    environment:
      - PHP_TZ=America/New_York
      - DB_CONNECTION=mysql
      - DB_HOST=lychee_db
      - DB_PORT=3306
      - DB_DATABASE=lychee
      - DB_USERNAME=lychee
      - DB_PASSWORD=${DB_PASSWORD}
      - STARTUP_DELAY=5
    restart: unless-stopped
    depends_on:
      - lychee_db

networks:
  lychee:

volumes:
  mysql:
````

.env:
```
PUID=1000
PGID=1000
PHP_TZ=America/New_York
DB_CONNECTION=mysql
DB_HOST=db
DB_PORT=3306
DB_DATABASE=lychee
DB_USERNAME=lychee
DB_PASSWORD=password_here
APP_URL='https://domain.tld'
```

Docker-log:
```
lychee       | **** Make sure the /conf and /uploads folders exist ****
lychee       | **** Create the symbolic link for the /uploads folder ****
lychee       | **** Create the symbolic link for the /sym folder ****
lychee       | **** Create the symbolic link to the old Lychee-Laravel folder ****
lychee       | **** Copy the .env to /conf ****
lychee       | **** Inject .env values ****
lychee       | **** Generate the key (to make sure that cookies cannot be decrypted etc) ****
lychee       | 
lychee       | **************************************
lychee       | *     Application In Production!     *
lychee       | **************************************
lychee       | 
lychee       | Command Canceled!
lychee       | **** Migrate the database ****
lychee       | 
lychee       | 
lychee       | In Connection.php line 678:
lychee       |                                                                                
lychee       |   SQLSTATE[HY000] [2002] Connection timed out (SQL: select * from information  
lychee       |   _schema.tables where table_schema = lychee and table_name = migrations and   
lychee       |   table_type = 'BASE TABLE')                                                   
lychee       |                                                                                
lychee       | 
lychee       | In Exception.php line 18:
lychee       |                                                
lychee       |   SQLSTATE[HY000] [2002] Connection timed out  
lychee       |                                                
lychee       | 
lychee       | In PDOConnection.php line 38:
lychee       |                                                
lychee       |   SQLSTATE[HY000] [2002] Connection timed out  
lychee       |                                                
lychee       | 
lychee       | **** Check user.css exists and symlink it ****
lychee       | **** Create user and use PUID/PGID ****
lychee       |  	User UID :	1000
lychee       |  	User GID :	1000
lychee       | **** Set Permissions ****
lychee       | **** Setup complete, starting the server. ****
```
